version: "3.9"

services:
  database_officium:
    image: postgres
    container_name: database_officium
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: officium_backend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_officium
    depends_on:
      - database_officium

volumes:
  pgdata:
    driver: local